### ISSUE TITLE
With versión PG 9.3 not work with different schemas to public. 

### ISSUE THREAD

**Issue by ghost** [gitsql/PostgreSQL-Edition-Windows#2]
I create a database with two schema (public and private).  If I test gitSql (Version demo), only view the schema from public.

**Comment by anupsaund** [comment]
Hi @dbarcena ,

Do you have a working example we can use please?

**Comment by ghost** [comment]
`create database test2016;`
I Open the Query and...
`create SCHEMA private AUTHORIZATION postgres;`
`CREATE TABLE test1 (   a bigint ) WITH (   OIDS=FALSE );`
`ALTER TABLE test1   OWNER TO postgres;`
`CREATE TABLE private.test2 (   a bigint ) WITH (   OIDS=FALSE );`
`ALTER TABLE private.test2   OWNER TO postgres;`

Only 2 simple tables.

![captura](https://cloud.githubusercontent.com/assets/8384855/19678136/cd7285b6-9a9c-11e6-8ef7-46f3ebb4cbfc.PNG)

**Comment by ghost** [comment]
## 

## -- PostgreSQL database dump

-- Dumped from database version 9.3.10
-- Dumped by pg_dump version 9.5.1

-- Started on 2016-10-25 10:23:21

SET statement_timeout = 0;
SET lock_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SET check_function_bodies = false;
SET client_min_messages = warning;
SET row_security = off;

## 

-- TOC entry 8 (class 2615 OID 47221)

## -- Name: private; Type: SCHEMA; Schema: -; Owner: postgres

CREATE SCHEMA private;

ALTER SCHEMA private OWNER TO postgres;

## 

-- TOC entry 1 (class 3079 OID 11750)

## -- Name: plpgsql; Type: EXTENSION; Schema: -; Owner: 

CREATE EXTENSION IF NOT EXISTS plpgsql WITH SCHEMA pg_catalog;

## 

-- TOC entry 1942 (class 0 OID 0)
-- Dependencies: 1

## -- Name: EXTENSION plpgsql; Type: COMMENT; Schema: -; Owner: 

COMMENT ON EXTENSION plpgsql IS 'PL/pgSQL procedural language';

SET search_path = private, pg_catalog;

SET default_tablespace = '';

SET default_with_oids = false;

## 

-- TOC entry 173 (class 1259 OID 47228)

## -- Name: test2; Type: TABLE; Schema: private; Owner: postgres

CREATE TABLE test2 (
    a bigint
);

ALTER TABLE test2 OWNER TO postgres;

SET search_path = public, pg_catalog;

## 

-- TOC entry 172 (class 1259 OID 47222)

## -- Name: test1; Type: TABLE; Schema: public; Owner: postgres

CREATE TABLE test1 (
    a bigint
);

ALTER TABLE test1 OWNER TO postgres;

SET search_path = private, pg_catalog;

## 

-- TOC entry 1934 (class 0 OID 47228)
-- Dependencies: 173

## -- Data for Name: test2; Type: TABLE DATA; Schema: private; Owner: postgres

COPY test2 (a) FROM stdin;
.

SET search_path = public, pg_catalog;

## 

-- TOC entry 1933 (class 0 OID 47222)
-- Dependencies: 172

## -- Data for Name: test1; Type: TABLE DATA; Schema: public; Owner: postgres

COPY test1 (a) FROM stdin;
.

## 

-- TOC entry 1941 (class 0 OID 0)
-- Dependencies: 6

## -- Name: public; Type: ACL; Schema: -; Owner: postgres

REVOKE ALL ON SCHEMA public FROM PUBLIC;
REVOKE ALL ON SCHEMA public FROM postgres;
GRANT ALL ON SCHEMA public TO postgres;
GRANT ALL ON SCHEMA public TO PUBLIC;

-- Completed on 2016-10-25 10:23:21

## 

## -- PostgreSQL database dump complete

**Comment by davesinghs** [comment]
Issue #3 is blocking this.

**Comment by jamesjburton** [comment]
At the moment, we only discover the default schema that is assigned to a database.

**Comment by jamesjburton** [comment]
Requires a discussion to see if gitSQL are to include this functionality as a feature.

**Comment by MarkWojciechowicz** [comment]
I am just evaluating this product as well.  This enhancement would be essential, if my team were to take on this tool as we use multiple schemas in our environment.  
There is no other tool on the market to easily get Postgres into git, so I would very much appreciate the feature.

**Comment by jamesjburton** [comment]
I have managed to list out the schema names using @dbarcena's example script.

![schemas](https://cloud.githubusercontent.com/assets/23381149/20839085/1b33dcfe-b8a3-11e6-9088-1b8b51f2c143.png)

This proves that we should be able to add the feature, but it will require changes to UI and Export/Import routines.

UI - We need to display the schema names as part of the database drop down.
Import - We need to be able to detect a schema name, and import into schema X.
Export - We need to export with schema name instructions for an import to detect.

**Comment by jamesjburton** [comment]
![progress](https://cloud.githubusercontent.com/assets/23381149/23320830/456fad4a-fad4-11e6-825c-9af6a7c56e4e.png)

"Entire Database" Option also added for easy of use.

**Comment by jamesjburton** [comment]
@davesinghs Ready for QA.

**Comment by mariascott** [comment]
Released
