### ISSUE TITLE
Cannot Connect to Postgres - Fatal: database "<my user name>" does not exist

### ISSUE THREAD

**Issue by MarkWojciechowicz** [gitsql/PostgreSQL-Edition-Windows#3]
When trying to connect to a database in postgres, there are 4 fields to enter:
 - host
 - port
 - Username
 - password

A field for database appears to be missing.  When these values are entered, the following error is returned:

> Connection Error.  There was an error with your connection:  FATAL: database "<user name entered>" does not exist. 

Supposing that the fields were mislabeled, I tried putting the database in the username field and the username in the password field.  This threw the error that the role does not exist (for the database name entered).  So it definitely appears to be the username field.

I would expect there to be a field for database, rather than assuming a connection to the default database.

Mark

**Comment by davesinghs** [comment]
@MarkWojciechowicz  - thank you for raising this issue.

You are right - a database field should be available.

We will look at getting this into the next release.

**Comment by jamesjburton** [comment]
@davesinghs : The current functionality is to discover all databases for the user login from screen 1.

Screen 2 offers a drop down for the user to pick a database.

@MarkWojciechowicz Could it be that the username logging on does not have access to any databases?

**Comment by jamesjburton** [comment]
@MarkWojciechowicz I ran a test to see if it is possible to log into a new user account with no database assigned to it and it fails to log in, which is a BUG.

The bug is actually related to #1.

I applied the fix for #1 and the login now works correctly.

Then the 2nd page will present a list of available databases for the logged in user.

**Comment by mariascott** [comment]
Released in version 1.0.1

**Comment by MarkWojciechowicz** [comment]
This worked for me - thanks for fixing!
