### ISSUE TITLE
Unable to export stored procedures

### ISSUE THREAD

**Issue by rynx91** [gitsql/PostgreSQL-Edition-Windows#4]
Hi there, I am using the PostgreSQL free edition and I was able to export tables, views and sequences. However, the program failed to detect the stored procedures, hence I'm unable to export them out. Please advise on this.

**Comment by mariascott** [comment]
Thank you for getting in touch.
We tested this and it is indeed a BUG in the product.

Our QA environment has some additional flags which enable discovery of stored procedures (Functions).

We will look into turning round a fix for this as soon as possible.

**Comment by rynx91** [comment]
OK, noted. Thank you! :)

Sent from my HTC

----- Reply message -----

**Comment by jamesjburton** [comment]
Code update complete, ready for QA.

**Comment by mariascott** [comment]
Released as Hot Fix. 
Available as an auto update, or via a new download from the website.

**Comment by rynx91** [comment]
Thank you very much for the prompt response. I have downloaded the new version and the software is now able to detect my stored procedures and export them out. But, some of the exported files are empty.
I am using this sample database to try it out: http://www.postgresqltutorial.com/postgresql-sample-database/
As you can see, there are 8 functions in this sample. However, only 2 of the exported functions have contents(public._group_concat(text,text),public.last_day(timestamp without time zone).
Kindly advise on this. Thanks :)

**Comment by mariascott** [comment]
Thank you for the details.

We found more code errors, which were preventing the export of the functions.

A new release is scheduled today, V 1.1.2.

**Comment by mariascott** [comment]
Released as 1.1.2 - Through Auto Update, or Download from the website. 👍

**Comment by rynx91** [comment]
I face the same problem again when I use your product on another database. The functions are not detected hence cannot be exported.

**Comment by alexandercalhoun** [comment]
It's been a while, but this bug still seems present while evaluating the functionality in the free edition v1.1.4. No functions/procedures are found, and thus cannot be exported. Did this only affect the free edition, or also the paid edition?
