### ISSUE TITLE
pg 9.6 data restore not working. 

### ISSUE THREAD

**Issue by grahamglover** [gitsql/PostgreSQL-Edition-Windows#6]
Data restore says 100% complete but the table is empty. I also ran the SQL manually to restore in pgAdmin and says completed but no data.

[public.component_params.txt](https://github.com/gitsql/PostgreSQL-Edition-Windows/files/2938759/public.component_params.txt)

**Comment by mariascott** [comment]
Hi @grahamglover - let us know if this is still an issue.
