### ISSUE TITLE
Test connection expects database called postgres

### ISSUE THREAD

**Issue by BlaineRen** [gitsql/PostgreSQL-Edition-Windows#7]
Trying to test a connection to my postgres database, I get the following error:

error: could not connect to server: FATAL: database "postgres" does not exist

My database is not named postgres and so I can't connect.  I couldn't see a way to change the default name of the database it tries to connect to.

Any ideas?

**Comment by mariascott** [comment]
Hi @BlaineRen,

gitSQL PostgreSQL edition will fall back to postgres as the default database if the user credentials are correct, but no default schema can be found for the user.

Does the user have a default database granted?
